-- Snowflake Orders pipeline: Azure stage -> COPY INTO staging -> MERGE, run by a scheduled TASK.
-- Snowflake encrypts all data at rest (AES-256) and in transit (TLS 1.2+). For customer-managed
-- keys, enable Tri-Secret Secure (Business Critical edition).
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ORDERS_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS ORDERS_DB;
CREATE SCHEMA IF NOT EXISTS ORDERS_DB.SALES;

-- Roles
CREATE ROLE IF NOT EXISTS ORDERS_LOADER;
CREATE ROLE IF NOT EXISTS ORDERS_READER;
GRANT USAGE ON WAREHOUSE ORDERS_WH TO ROLE ORDERS_LOADER;
GRANT USAGE ON WAREHOUSE ORDERS_WH TO ROLE ORDERS_READER;
GRANT USAGE ON DATABASE ORDERS_DB TO ROLE ORDERS_LOADER;
GRANT USAGE ON DATABASE ORDERS_DB TO ROLE ORDERS_READER;
GRANT ALL ON SCHEMA ORDERS_DB.SALES TO ROLE ORDERS_LOADER;
GRANT USAGE ON SCHEMA ORDERS_DB.SALES TO ROLE ORDERS_READER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ORDERS_LOADER;

-- Storage integration to the ADLS landing container (Entra ID consent; no keys stored).
CREATE STORAGE INTEGRATION IF NOT EXISTS ORDERS_AZURE_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '<tenant-id>'
  STORAGE_ALLOWED_LOCATIONS = ('azure://<storageaccount>.blob.core.windows.net/landing/snowflake/');
-- DESC STORAGE INTEGRATION ORDERS_AZURE_INT;  -> open AZURE_CONSENT_URL, then grant the
-- Snowflake app "Storage Blob Data Reader" on the storage account.
GRANT USAGE ON INTEGRATION ORDERS_AZURE_INT TO ROLE ORDERS_LOADER;

USE ROLE ORDERS_LOADER;
USE WAREHOUSE ORDERS_WH;
USE SCHEMA ORDERS_DB.SALES;

CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID STRING NOT NULL PRIMARY KEY, ORDER_DATE DATE, CUSTOMER_ID STRING, CUSTOMER_NAME STRING,
  REGION STRING, PRODUCT STRING, CATEGORY STRING, QUANTITY INT,
  UNIT_PRICE NUMBER(12,2), TOTAL_AMOUNT NUMBER(14,2), STATUS STRING, UPDATED_AT TIMESTAMP_NTZ
) CLUSTER BY (ORDER_DATE);

CREATE TRANSIENT TABLE IF NOT EXISTS ORDERS_STAGING LIKE ORDERS;

CREATE FILE FORMAT IF NOT EXISTS ORDERS_CSV TYPE = CSV SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE IF NOT EXISTS ORDERS_LANDING
  STORAGE_INTEGRATION = ORDERS_AZURE_INT
  URL = 'azure://<storageaccount>.blob.core.windows.net/landing/snowflake/'
  FILE_FORMAT = ORDERS_CSV;

CREATE OR REPLACE PROCEDURE REFRESH_ORDERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  TRUNCATE TABLE ORDERS_STAGING;
  -- COPY's load metadata skips files already loaded in the last 64 days.
  COPY INTO ORDERS_STAGING FROM @ORDERS_LANDING PATTERN = '.*[.]csv' ON_ERROR = 'ABORT_STATEMENT';
  MERGE INTO ORDERS t
  USING (SELECT * FROM ORDERS_STAGING
         QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY UPDATED_AT DESC) = 1) s
  ON t.ORDER_ID = s.ORDER_ID
  WHEN MATCHED AND s.UPDATED_AT >= t.UPDATED_AT THEN UPDATE SET
    ORDER_DATE = s.ORDER_DATE, CUSTOMER_ID = s.CUSTOMER_ID, CUSTOMER_NAME = s.CUSTOMER_NAME,
    REGION = s.REGION, PRODUCT = s.PRODUCT, CATEGORY = s.CATEGORY, QUANTITY = s.QUANTITY,
    UNIT_PRICE = s.UNIT_PRICE, TOTAL_AMOUNT = s.TOTAL_AMOUNT, STATUS = s.STATUS, UPDATED_AT = s.UPDATED_AT
  WHEN NOT MATCHED THEN INSERT VALUES (
    s.ORDER_ID, s.ORDER_DATE, s.CUSTOMER_ID, s.CUSTOMER_NAME, s.REGION, s.PRODUCT, s.CATEGORY,
    s.QUANTITY, s.UNIT_PRICE, s.TOTAL_AMOUNT, s.STATUS, s.UPDATED_AT);
  RETURN 'ok';
END;
$$;

CREATE OR REPLACE TASK REFRESH_ORDERS_HOURLY
  WAREHOUSE = ORDERS_WH
  SCHEDULE = 'USING CRON 15 * * * * UTC'
AS CALL REFRESH_ORDERS();
ALTER TASK REFRESH_ORDERS_HOURLY RESUME;

-- Read-only grants for the MCP server
GRANT SELECT ON TABLE ORDERS_DB.SALES.ORDERS TO ROLE ORDERS_READER;

USE ROLE ACCOUNTADMIN;
-- Service user for the MCP server, key-pair auth only (private key in Key Vault: snowflake-private-key).
CREATE USER IF NOT EXISTS MCP_ORDERS_READER
  TYPE = SERVICE
  DEFAULT_ROLE = ORDERS_READER
  DEFAULT_WAREHOUSE = ORDERS_WH
  RSA_PUBLIC_KEY = '<contents of rsa_key.pub without header/footer>';
GRANT ROLE ORDERS_READER TO USER MCP_ORDERS_READER;

-- Optional: restrict the service user to the Container Apps egress IPs.
-- CREATE NETWORK POLICY MCP_ONLY ALLOWED_IP_LIST = ('<aca-outbound-ip>');
-- ALTER USER MCP_ORDERS_READER SET NETWORK_POLICY = MCP_ONLY;
